// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SpaceData.Data;

#nullable disable

namespace SpaceData.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260609233901_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SpaceData.Models.Agente", b =>
                {
                    b.Property<string>("IdAgente")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("ID_AGENTE");

                    b.Property<string>("DtNascimento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("DT_NASCIMENTO");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("ESPECIALIDADE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NM_AGENTE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ST_AGENTE");

                    b.HasKey("IdAgente");

                    b.ToTable("T_AGENTE");
                });

            modelBuilder.Entity("SpaceData.Models.AgenteMissao", b =>
                {
                    b.Property<string>("IdAgenteMissao")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("IdAgente")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("IdMissao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("RelatorioMissao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.HasKey("IdAgenteMissao");

                    b.HasIndex("IdAgente");

                    b.HasIndex("IdMissao");

                    b.ToTable("T_AGENTE_MISSAO");
                });

            modelBuilder.Entity("SpaceData.Models.Missao", b =>
                {
                    b.Property<string>("IdMissao")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("DtInicio")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<int>("DuracaoEstimada")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NomeMissao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdMissao");

                    b.ToTable("T_MISSAO");
                });

            modelBuilder.Entity("SpaceData.Models.AgenteMissao", b =>
                {
                    b.HasOne("SpaceData.Models.Agente", "Agente")
                        .WithMany("AgenteMissoes")
                        .HasForeignKey("IdAgente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpaceData.Models.Missao", "Missao")
                        .WithMany("AgenteMissoes")
                        .HasForeignKey("IdMissao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agente");

                    b.Navigation("Missao");
                });

            modelBuilder.Entity("SpaceData.Models.Agente", b =>
                {
                    b.Navigation("AgenteMissoes");
                });

            modelBuilder.Entity("SpaceData.Models.Missao", b =>
                {
                    b.Navigation("AgenteMissoes");
                });
#pragma warning restore 612, 618
        }
    }
}
